export const SHOP_MODULE_NAME = 'shopReducer'

const actions = {
	FETCH_PRODUCTS_REQUEST: 'FETCH_PRODUCTS_REQUEST',
	FETCH_PRODUCTS_SUCCESS: 'FETCH_PRODUCTS_SUCCESS',
	FETCH_PRODUCTS_FAILURE: 'FETCH_PRODUCTS_FAILURE',

	SET_FILTER_REQUEST: 'SET_FILTER_REQUEST',
	SET_FILTER_SUCCESS: 'SET_FILTER_SUCCESS',
	SET_FILTER_FAILURE: 'SET_FILTER_FAILURE',

	ADD_FAVORITE_REQUEST: 'ADD_FAVORITE_REQUEST',
	ADD_FAVORITE_SUCCESS: 'ADD_FAVORITE_SUCCESS',
	ADD_FAVORITE_FAILURE: 'ADD_FAVORITE_FAILURE',
};

export default actions;
